### ISSUE TITLE
Problema al serializar excepciones

### ISSUE THREAD

**Issue by arypbatista** [gobstones/PyGobstones#31]
Dado el siguiente programa:

```
program { 
  return(isEmpty([x]))
}
```

Si corro el anális semántico sobre XGobstones, me dice que el programa es correcto (nótese que no estoy inicializando x).

Si ejecuto el programa se queda "colgado" en:

-> Haciendo análisis semántico.
-> Compilando.
-> Ejecutando el programa.

y en la consola me muestra el siguiente Trace:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
    send(obj)
PicklingError: Can't pickle <class 'lang.gbs_vm.GbsVmException'>: it's not the same object as lang.gbs_vm.GbsVmException
```

Si hago análisis semántico pero en Gobstones, también se queda "colgado" y  la consola me tira el Trace:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
    send(obj)
PicklingError: Can't pickle <class 'lang.bnf_parser.ParserException'>: it's not the same object as lang.bnf_parser.ParserException
```

Por si les sirve datos del entorno:

Linux kernel 3.16.0-4-amd64
Debian GNU/Linux 8.0 (jessie)
Python 2.7.9
python-qt4 4.11.2+dfsg-1
PyGobstones 1.2.1

**Comment by arypbatista** [comment]
No ocurre más.
